baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Vidit Khandelwal - Literature'
theme = "hugo-winston-theme"

[params]
  google_analytics_id = ""
  twitter_handle = "@viditkh"
  github_handle = "@csvidit"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
  highlightColor = '#E42023'
