baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'VIDIT KHANDELWAL LIT.'
theme = "hugo-winston-theme"

[params]
  google_analytics_id = ""
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
  highlightColor = '#E42023'
